### ISSUE TITLE
Antivirus Trojan Detection

### ISSUE THREAD

**Issue by Desaje13** [InfinityGhost/TabletDriver#16]
I know that it’s strange question but is this ok that my antivirus program writes that this driver is virus (Trojan)?
## Hardware/software information
Windows Version: 10 x64bit
Driver version: 0.3

**Comment by 0forzero** [comment]
I'm getting the same thing. Prob false positive.

**Comment by Desaje13** [comment]
> I'm getting the same thing. Prob false positive.

Don't really think that it's false positive tbh.

**Comment by 0forzero** [comment]
Ok Windows Defender and Kaspersky are both flagging it. For now I won't use the provided binary. Might try and compile from the source later and see what happens

**Comment by InfinityGhost** [comment]
# Very odd [VirusTotal results](https://www.virustotal.com/gui/file/1fd679d950babb5b596c380214451c4fd85057434a4bb5479b32a52d514fae97)

Honestly unsure where its getting this from. I'm going to build TabletDriver on a completely clean install of windows 10 in a virtual machine and see if I get the same results. This SHOULD be a false positive due to the nature of how the driver collects input data, plus its system for detecting framework installs and such matters.

# Behavior analysis of the two files that are compromised:

I can crop these up to multiple functions
1. [TabletDriverGUI.exe](https://www.virustotal.com/gui/file/7f1a9386e1e1fcb394101acc6a3c3dd8aea88ed0c275d908afec59220e9d9b4c/behavior/VirusTotal%20Jujubox)
   - .NET Framework detection
   - Debugger checking
2. [TabletDriverService.exe](https://www.virustotal.com/gui/file/7f1a9386e1e1fcb394101acc6a3c3dd8aea88ed0c275d908afec59220e9d9b4c/behavior/VirusTotal%20Jujubox)
   - Piping for console output
   - Requesting tablet inputs

I'm very certain that these are false positives, and possibly could have been used in the past in malware which would trigger these false positives. The source code is open, so you can build it yourself if you don't trust this anyway.

**Comment by InfinityGhost** [comment]
# Can confirm safe
I installed a completely clean install of Windows 10 x64 1903 on a fresh virtual machine in VMWare, completely isolated from my main machine (i'm running linux mint 19.2)

[VirusTotal Results for v0.3.1 Pre-release](https://www.virustotal.com/gui/file/43700474d7e60c01f643f48105f4bb9e7d7e8e40a44167335ee79c94eb2d0087/detection)

For now, I'm closing this issue. Feel free to build it yourself and test it though.

**Comment by BreadGit** [comment]
I am still getting reports from Windows Defender for the latest build of master:
![ApplicationFrameHost_2019-12-07_14-48-16](https://user-images.githubusercontent.com/58152441/70381534-c0966e80-1900-11ea-962c-f6b2d81d260c.png)
![firefox_2019-12-07_14-49-39](https://user-images.githubusercontent.com/58152441/70381541-d86df280-1900-11ea-9fd2-c6bf6b7f4eb3.png)

I realize that you've closed this issue along with other duplicates because you've tested this project against a clean install of windows, but these reports still seem to be happening for people despite that

I don't have any solutions to give and I'm sure finding a solution for this is probably tricky, but perhaps at least keep this issue open until people stop receiving AV reports

**Comment by InfinityGhost** [comment]
> I don't have any solutions to give and I'm sure finding a solution for this is probably tricky, but perhaps at least keep this issue open until people stop receiving AV reports

I'm likely going to archive this repository, my [latest project](https://github.com/InfinityGhost/OpenTabletDriver) will make this shit obsolete.

**Comment by TheTreeSee** [comment]
my pc doesn't let me download the file because he thinks there is a virus...

**Comment by exil0867** [comment]
![image-1578](https://user-images.githubusercontent.com/6927114/76630852-fa4ec500-6540-11ea-80d7-51962430d3a9.png)

**Comment by exil0867** [comment]
> I'm likely going to archive this repository, my [latest project](https://github.com/InfinityGhost/OpenTabletDriver) will make this shit obsolete.

@InfinityGhost Is OpenTabletDriver stable enough to be used?

**Comment by InfinityGhost** [comment]
> > I'm likely going to archive this repository, my [latest project](https://github.com/InfinityGhost/OpenTabletDriver) will make this shit obsolete.
> 
> @InfinityGhost Is OpenTabletDriver stable enough to be used?

Absolutely, but major changes are coming in a future release

**Comment by exil0867** [comment]
Just tried it, it fails to detect my Gaomon S620 tablet.

**Comment by InfinityGhost** [comment]
> Just tried it, it fails to detect my Gaomon S620 tablet.

DM me on discord @ `InfinityGhost#7843`
